#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

helmDefaults:
  wait: {{ .Values | get "global.default.wait" true }}

missingFileHandler: Error

releases:
  - name: {{ .Values | get "dockercreds.release.name" }}
    chart: ./secret-eric-docker-creds
    namespace: {{ .Values | get "global.app.namespace" }}
    installed: {{ .Values | get "global.app.enabled" }}
