modelVersion: "2.0"
flavor: "Generic"
service:
  name: "Helmfile Executor"
  design_countries:
   - IE
  sw_compilation_country: IE
  release_responsible: BDGSBECH
  design_responsible: BDGSBECH
  encryption_status: Completed
  documents:
    import: documents.yaml
  top_product:
    number: APR 201 514
    designation: Helmfile Executor
    description: |-
      This service will accept helmfile or integration chart archives and apply them to a target cluster.
      This results in one or more Helm releases installed on the cluster in one or more namespaces, in parallel/sequential groups.
      Helmfile leverages the helm-diff plugin to find out what Helm releases need to be updated and delegates the execution to Helm itself.
      To support legacy this service will also accept integration charts for those who haven't migrated to Helmfile yet
    alias:
      - eric-lcm-helm-executor
    includes:
      # PRI
      - eridoc: 109 21-APR 201 514/0
        step_strategy: generate
      # Test Specification
      - eridoc: 152 41-APR 201 514/0
        step_strategy: highest revision letter
      # Test Report
      - eridoc: 152 83-APR 201 514/0
        step_strategy: highest ordinal number
      # Risk Assessment doc
      - eridoc: 006 64-APR 201 514/0
        step_strategy: highest revision letter
      # Secure Coding Report
      - eridoc: 0360-APR 201 514/0
        step_strategy: highest revision letter
      # VA Report
      - eridoc: 1597-APR 201 514/0
        step_strategy: highest revision letter
      - prim: 1/FAL 115 3215
        rstate: R1A
      - prim: 3/FAL 115 3215
        rstate: R1A
      - prim: 5/FAL 115 3215
        rstate: R1A
      - prim: 7/FAL 115 3215
        rstate: R1A
  src_products:
    - label: "Source"
      designation: Helmfile Executor Source
      description: >
        The source code for Helmfile Executor microservice
        implemented in java
      number: CAV 101 964
  derivative_products:
    - label: "helm"
      designation: Helmfile Executor Helm Chart
      description: >
        The Helm Chart configuration file of Helmfile Executor microservice
        to deploy on a Kubernetes cluster
      number: CXD 101 181
      alias:
        - eric-lcm-helm-executor
      derivedFrom:
        munin: CAV 101 964
    - label: "image"
      designation: Helmfile Executor Image
      description: >
        The container image of Helmfile Executor contains the example microservice
        with a REST API
      number: CXU 101 1119
      includes:
        - munin: CXC 201 2032
          version: ##CBOS_VERSION##
          secondPartyProduct: "True"
        - munin: CXC 201 2031
          version: ##CBOS_VERSION##
          secondPartyProduct: "True"
      uses_foss:
        - dependencies_file: ../../generated/dependencies/dependencies-3pp.yaml  #  Dependencies YAML
        - foss_usage: foss.usage.yaml
      uses_encryption:
        - import: encryptions.yaml
      derivedFrom:
        munin: CAV 101 964
    - label: "initcontainer"
      designation: Helmfile Executor InitContainer Image
      description: >
        The init container image of Helmfile Executor, used within
        the eric-lcm-helm-executor environment to initialize HFE and setup the
        communication among Document Database PG and HFE.
      number: CXU 101 1169
      includes:
        - munin: CXC 201 2032
          version: ##CBOS_VERSION##
          secondPartyProduct: "True"
        - munin: CXC 201 2031
          version: ##CBOS_VERSION##
          secondPartyProduct: "True"
      uses_foss:
        - dependencies_file: ../../generated/dependencies/dependencies-3pp.yaml  #  Dependencies YAML
        - foss_usage: foss.usage.yaml
      uses_encryption:
        - import: encryptions.yaml
      derivedFrom:
        munin: CAV 101 964
